version: "3.9"

services:
  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /databases/mongo:/data/db
    ports:
      - 27017:27017


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      
  neo4j:
    image: neo4j:3.5.3
    volumes:
      - /databases/neo4j:/data
    ports:
      - 7474:7474
      - 7687:7687

  mssql: 
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "1234myFancyPasswort"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
      - 1431:1431
      - 1434:1434