version: "3.9"

services:
  mongo:
    image: mongo:4.4.11-rc0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - "mongo"

  neo4j:
    image: neo4j:3.5.3
    volumes:
      - /databases/neo4j:/data
    ports:
      - 7474:7474
      - 7687:7687

  mssql: 
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "changeMe1234"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
      - 1431:1431
      - 1434:1434 
